---
title: "Lab 1"
description: "Configuring a 7-segment display and LEDs"
author: "Troy Kaufman"
date: "9/2/24"
draft: false
---

Hi all! I recently finsihed the first lab in MicroPs, and it was overwhelmingly satisfying to see my hardwork pour into
a successful project. Despite the premise being to turn on LEDs in various fashions, the lab was gruelling in some aspects. 
This lab was a neat introduction to the digital design world.

The most exciting part about the lab was designing the counter needed to blink an LED at 2.4 Hz. There is a handful of ways to perform this operation, and I did end up trying some of them out to see which method would produce the closest blinking freqeuncy. It was fun trying this out. However, this ended up being one of the most frustrating parts of the lab as well. I incorrectly gave my counter 22 bits when in reality it needed 25 bits to operate. This oversight caused hours of pain and eventual embarassment aft the bug was caught.

Overall, this was an entertaining lab that showed me the FPGA design flow in Lattice Radiant. It took sometime getting used to the new tool, howeever, I don't doubt that with some practice I can maneuver around with no difficulty.  