---
title: "Reflection 4"
description: "Music Playing MCU Bare Metal"
author: "Troy Kaufman"
date: "10/3/24"
draft: false
---


Lab 4 was concerned with exposing students to bare metal programming on an MCU to produce the song, Fur Elise. This lab took a lot of patience because there were many configuration registers that needed to be accounted for withing the 1600 page document. After hours of reading through documentation, it was immensely satifying to see my design output a square wave on the oscilloscope and even more so when the song played in its entirety from the speaker. 

Besides the fact that it was very easy to leave out an important register in the code, my most frustrating bug came with my delay function. It was frustrating because my pwm function was working just fine - which is a more complex version of the delay function! I was making two major mistakes: wrong oscilloscope interpretations and missed configuring two parts of a timer register. The fatal flaw that held me back for hours was the wrong oscillscope interpretation. In my mind I though that the delay was being produced correctly because the next note in the song would be played after some time...when I pressed the next step button in the debugger. Essentially, I wasn't checking my delay function at all on the oscilloscope - yikes.

Overall, this was a fun lab to complete with some minor hiccups here and there. The main lesson I learned from this was to take notes on all the important registers that MIGHT need to be configured in my design to build a record. Doing this could have saved me a handful of hours of rereading documentation. 