---
title: "Reflection 5"
description: "General Thoughts About The Course Thus Far"
author: "Troy Kaufman"
date: "10/7/24"
draft: false
---

The past two weeks have been incredibly fun and satisfying. I managed to finish lab 4 (timers), and I'm very close to finishing lab 5 (interrupts). Through the past 7 weeks, I've learned that this course is a debugging masterclass more than anything else. Creating a design to solve a problem is not so hard to do. Constantly monitoring input and output signals and everything in between are the most difficult parts. 

Frustration often kicks in hard and fast. The best way I've managed to combat this is to step away from the workbench and walk around the orange trees behind the engineering building. This affords me time to think about other things in life. This class is difficult, time consuming, and thought provoking. Everyone I have talked to has said that they have shed tears over this class at one point or another this semester. It's a natural thing to be stressed out, but it's how we react to the stress that truly defines ourselves as problem solvers. If anybody could do it, then MicroPs would be a 100 person class but that's not reality. 

I have learned more this semester in this one class compared to the rest of my time at Mudd. I'm proud of myself for being independent in this course. It has forced me to think about different approaches and how to implement them. In other classes, many students work in groups to get psets or labs done. I've noticed some people in this class tend to work in pairs/groups which is completely justified. However, I think they're missing the main purpose that this course is providing them: an opportunity to struggle - ALONE - on NEW and COMPLEX systems. 

My girlfriend hates this class because of how much time I devote to it. I often joke around and say that the digital lab is my second home (Xavier, the GOATED engineering assistant, has commented on this too). I'm happy that I'm already halfway through the labs, but I'm saddened by it because I know that I won't experience this with another class at Mudd ever again. This course has brought me joy, tears, maniacal laughter, fist pumps in the air, frustration, expletive comments (happy and sad), and best of all satisfaction. MicroPs has brought me on a rollercoaster of emotions and I ABSOLUTELY LOVE IT!!!