---
title: "Reflection 6"
description: "Labs 4/5 going into fall break"
author: "Troy Kaufman"
date: "10/14/24"
draft: false
---

It's been a stressful week due to midterms, however, fall break is finally upon us. I was able to get my interrupt lab checked off for proficiency, but my timer lab did not pass. This was due to my scaled down clock input to the timer being too small which forced my auto-reload register counter to become a small and sometimes odd value. This small and off value caused inconsistencies in the delay and note frequenices. Simply decreasing the prescalar value fixed everything.

I'm currently attempting the lab 5 excellence mark and it has been a familiar story to completing labs 2 and 3. Two hours into debugging, I finally noticed that my HIGH logic level inputs to the MCU were set in the forbidden zone. This was weird because my logic level inputs were fine when I had a rising edge interrupt system. Eventually, I got everything to work and I will be getting excellence on labs 4 and 5. 


More recently, I have been planning out my final project - image edge detection. A camera would take an image and send it to the MCU where the DMA would transfer the data in a double buffer system to an SRAM. While one buffer was receiving data and waiting for an interrupt to trigger upon the buffer being filled, the other buffer would send its data to the core to be processed into a grayscale format. Another DMA channel would store this in SRAM until the FPGA would trigger a hardware interrupt event. When this would happen, the second channel would send its data over SPI to the FPGA to finally have the edge detection filter applied to the image. 

Both the FPGA and MCU contain a limited amount of resources so it was essential to choose what image processing steps would take place and where it would happen to conserve precious resources like adders, multipliers, and embedded RAM. 

This is going to be a really fun project! 